global using FluentValidation;
global using FluentValidation.Results;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Localization;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Linq;
global using System.Reflection;
global using System.Text.Json.Nodes;
global using Biwen.Settings;
global using Biwen.Settings.Domains;
global using FindTypes = Biwen.Settings.Infrastructure.TypeFinder.FindTypes;
global using ASS = Biwen.Settings.Infrastructure.Assemblies;
global using MSDA = System.ComponentModel.DataAnnotations;